services:
    db:
        image: postgres:12.4
        environment:
            POSTGRES_PASSWORD: enviu_dev
            POSTGRES_USER: postgres
        network_mode: host
        logging:
          driver: "json-file"
          options:
            max-file: "5"   # number of files or file count
            max-size: "10m" # file size
    blockscout:
        image: hristomavrodiev/blockscout:v4.1.1
        depends_on:
            - "db"
        ports:
            - "4001:4001"
        tty: true
        network_mode: host
        environment:
#            ETHEREUM_JSONRPC_HTTP_URL: http://127.0.0.1:8545
#            ETHEREUM_JSONRPC_TRACE_URL: http://127.0.0.1:8545
            ETHEREUM_JSONRPC_HTTP_URL: https://evm.iotabot.strangled.net
            ETHEREUM_JSONRPC_TRACE_URL: https://evm.iotabot.strangled.net
            ETHEREUM_JSONRPC_VARIANT: geth
            NETWORK: DEVNET-IOTA-EVM
            SUBNETWORK: WASP-EVM-1076
            COIN: MIOTA
            CHAIN_ID: 1076
            HOST: 127.17.0.1
            PORT: 4001
            DATABASE_URL: postgresql://postgres:@127.17.0.1:5432/explorer?ssl=false
            SECRET_KEY_BASE: 'VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221No' #Use mix phx.gen.secret to generate a new Secret Key Base
            BLOCKSCOUT_VERSION: 'v4.1.1-beta'
            LINK_TO_OTHER_EXPLORERS: 'false'
            SUPPORTED_CHAINS: '[ { "title": "IOTA Mainnet", "url": "https://explorer.iota.org/mainnet" }, { "title": "WASP-IF-EVM-1074", "url": "https://explorer.wasp.sc.iota.org/", "test_net?": true}]'
        logging:
          driver: "json-file"
          options:
            max-file: "5"   # number of files or file count
            max-size: "10m" # file size
